DEFAULT_MODEL = "openai/gpt-oss-20b:free"
#DEFAULT_MODEL = "google/gemma-4-26b-a4b-it:free"

TRANSLATION_MODEL = DEFAULT_MODEL
COPYWRITING_MODEL = DEFAULT_MODEL
SUMMARY_MODEL = DEFAULT_MODEL
RAG_MODEL = DEFAULT_MODEL
